SET DATA_PATH=D:\IUSTIN\DoinaData
python myTrain.py ^
--mu 3 ^
--k-img 6126 ^
--dropout 0.2 ^
--optimizer adam ^
--scheduler plateau ^
--my_format multimodal ^
--model mmbt ^
--train_file "train_bt" ^
--unlabeled_dataset "unlabeled_bt" ^
--unbalanced ^
--batch-size 1 ^
--gradient_accumulation_steps 16 ^
--epochs 50 ^
--dataset CrisisMMD ^
--task "humanitarian_orig" ^
--lr 1e-5 ^
--threshold 0.7 ^
--use-ema ^
--text_soft_aug "en-de-en" ^
--text_hard_aug "en-de-fr-en" ^
--lambda-u 1 ^
--data_path "%DATA_PATH%\data_splits" ^
--img_path "%DATA_PATH%" ^
--out "%DATA_PATH%\results\humanitarian_g16_dr02_ema1_lu1_mu3_im+de+defr_07may_x2"
